### your site title here

title: Bhaavanaa Thumu
description: Research Assistant at IIT Kharagpur

url: "https://bhaavanaa.github.io/" #custom url to be used instead of GitHub repository
email: #


highlighter: rouge
markdown: kramdown

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
# facebook: "#"
twitter: "https://twitter.com/_Bhaavanaa"
linkedin: "/in/bhaavanaa-thumu-48820517a/"
github: "https://github.com/bhaavanaa"
researchgate: "https://www.researchgate.net/profile/Bhaavanaa_Thumu"
# orcid: "#"

highlighter: rouge
markdown: kramdown

# Tracker
analytics:

#optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
